### PR TITLE
Get the dev GUI building on Windows

### LINKED ISSUE #5: Dev gui fails to build on windows (observed with commit d2a2a649)
There were two issues that needed correcting for me to get the build working.
Firstly: attempting to compile main.cpp was producing the following error:
```
error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\Users\ethan\repos\tau5\gui\build\tau5-gui-dev.vcxproj]
```
After a bit of research, making sure that `Q_OS_WIN` is defined before it is referenced appeared to solve that issue.

Secondly: main.cpp still failed to build with further errors. I asked AI for advice for this one, but there appear to be header file conflicts over multiple Winsock versions. It suggested that defining `WIN32_LEAN_AND_MEAN` would solve that issue. The build appeared to complete successfully after that, but I am not 100% familiar with all the implications that defining that variable may have, so I'll leave it up to someone else as to whether that's the correct fix for that one.

On the chance that these are indeed correct fixes for these issues, I'll open up a PR.

### PR DESCRIPTION
**Pull request by ethancrawford**
There appeared to be two issues that needed fixing:
- `Q_OS_WIN` was not defined before it was referenced
- Header file conflicts that included multiple Winsock versions

Though defining WIN32_LEAN_AND_MEAN appeared to solve the immediate build issue, I'm not 100% sure whether it has any undesirable flow-on effects - so please feel free to close or modify this PR if desired.
(Fixes https://github.com/samaaron/tau5/issues/5)

### CODE REVIEW

**Comment by samaaron** [comment]
Thanks!
